service: demo-serverless
org: bijaksherry
frameworkVersion: ^3.22.0

custom:
  serverlessPluginTypescript:
    tsConfigFileLocation: './tsconfig.json'
  serverless-offline:
    noPrependStageInUrl: true
  # serverless-offline:
  #   httpPort: 4000
  #   websocketPort: 4001
  #   lambdaPort: 4002

provider:
  name: aws
  runtime : nodejs12.x
  versionFunctions: false
  memorySize: 512
  timeout: 30
  stage: dev
  region: 'ap-south-1'
  logs:
    restApi: true

# layers:
#   CredDemoModule:
#     path: node_modules
#     description: "Cred Operation involving the importance of layers"

functions:

  getUsers:
    handler: ./src/handler.getUsers
    events:
      - http:
          method: get
          path: users
          cors:
            origin: '*' # <-- Specify allowed origin
            headers: # <-- Specify allowed headers
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
            allowCredentials: false
    layers:
      - arn:aws:lambda:ap-south-1:576875047862:layer:demo_serverless_layer:1

  postUserResp:
    handler: ./src/handler.postUserResp
    events:
      - http:
          method: post
          path: postUser
          cors:
            origin: '*' # <-- Specify allowed origin
            headers: # <-- Specify allowed headers
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
            allowCredentials: false
    layers:
      - arn:aws:lambda:ap-south-1:576875047862:layer:demo_serverless_layer:1

  deleteUserResp:
    handler: ./src/handler.deleteUserResp
    events:
      - http:
          method: delete
          path: deleteUser
          cors:
            origin: '*'
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
            allowCredentials: false
    layers:
      - arn:aws:lambda:ap-south-1:576875047862:layer:demo_serverless_layer:1

  updateUser:
      handler: ./src/handler.updateUser
      events:
        - http:
            method: put
            path: updateUser
            cors:
              origin: '*' # <-- Specify allowed origin
              headers: # <-- Specify allowed headers
                - Content-Type
                - X-Amz-Date
                - Authorization
                - X-Api-Key
                - X-Amz-Security-Token
                - X-Amz-User-Agent
              allowCredentials: false
      layers:
        - arn:aws:lambda:ap-south-1:576875047862:layer:demo_serverless_layer:1

  getUserViaId:
      handler: ./src/handler.getUserViaId
      events:
        - http:
            method: get
            path: getuserbyid
            cors:
              origin: '*' # <-- Specify allowed origin
              headers: # <-- Specify allowed headers
                - Content-Type
                - X-Amz-Date
                - Authorization
                - X-Api-Key
                - X-Amz-Security-Token
                - X-Amz-User-Agent
              allowCredentials: false
      layers:
        - arn:aws:lambda:ap-south-1:576875047862:layer:demo_serverless_layer:1

  restApi:
      handler: ./src/handler.restApi
      events:
        - http:
            method: get
            path: restfullApi
            cors: 
              origin: '*'
              headers: # <-- Specify allowed headers
                - Content-Type
                - X-Amz-Date
                - Authorization
                - X-Api-Key
                - X-Amz-Security-Token
                - X-Amz-User-Agent
              allowCredentials: false
      layers:
        - arn:aws:lambda:ap-south-1:576875047862:layer:demo_serverless_layer:1

  currentTime:
      handler: ./src/handler.currentTime
      events:
        - http:
            method: get
            path: currentTime
            cors:
              origin: '*'
              headers: # <-- Specify allowed headers
                - Content-Type
                - X-Amz-Date
                - Authorization
                - X-Api-Key
                - X-Amz-Security-Token
                - X-Amz-User-Agent
              allowCredentials: false
      layers:
        - arn:aws:lambda:ap-south-1:576875047862:layer:demo_serverless_layer:1

  httpApi:
      handler: ./src/handler.httpApi
      events:
        - http:
            method: get
            path: httpapi
            cors: 
              origin: '*'
              headers: # <-- Specify allowed headers
                - Content-Type
                - X-Amz-Date
                - Authorization
                - X-Api-Key
                - X-Amz-Security-Token
                - X-Amz-User-Agent
              allowCredentials: false
      layers:
        - arn:aws:lambda:ap-south-1:576875047862:layer:demo_serverless_layer:1  
  
  usersList:
      handler: ./src/handler.usersList
      events:
        - http:
            method: get
            path: userlistapi
            cors: 
              origin: '*'
              headers: # <-- Specify allowed headers
                - Content-Type
                - X-Amz-Date
                - Authorization
                - X-Api-Key
                - X-Amz-Security-Token
                - X-Amz-User-Agent
              allowCredentials: false
      layers:
        - arn:aws:lambda:ap-south-1:576875047862:layer:demo_serverless_layer:1  
        
plugins:
  - serverless-offline
  - serverless-plugin-typescript

package:
    individually: true
    excludeDevDependencies: true
    exclude:
      - 'node_modules/**'

 

  




